import Sidebar from "@/components/Sidebar";
import "./globals.css";
import { Providers } from "@/store/provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="w-full h-screen flex">
        <Providers>
          <Sidebar/>
          {children}
        </Providers>
        </body>
    </html>
  );
}
