import Sidebar from "@/components/Sidebar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="w-full h-screen flex">
        <Sidebar/>
        {children}
        </body>
    </html>
  );
}
